var uw;
(function (uw) {
    uw.dsConsts = {
        AccountEntity: { id: 1, name: 2, email: 3, pwd: 4, deviceId: 5, userServers: 6, channel: 7, sub_channel: 8, plat: 9, status: 10, channelId: 11 },
        ActivityEntity: { id: 1, title: 2, type: 3, iconType: 4, tiIconType: 5, startTime: 6, endTime: 7, items: 8, exValues: 9, content: 10, isOpen: 11, sort: 12 },
        ArenaBakEntity: { rank: 1, userId: 2, addTime: 3 },
        ArenaEntity: { id: 1, userId: 2, rank: 3, highRank: 4, fightRanks: 5 },
        ArenaLuckRankEntity: { id: 1, userId: 2, type: 3, rank: 4, sort: 5, userName: 6, addTime: 7, isSendAward: 8 },
        ArenaRecordEntity: { id: 1, userId: 2, userLvl: 3, userName: 4, userIcoinId: 5, userRank: 6, enemyId: 7, enemyLvl: 8, enemyName: 9, enemyIcoinId: 10, enemyRank: 11, changeRank: 12, isWin: 13, fightTime: 14, fightData: 15, uniqueKey: 16 },
        ChannelEntity: { id: 1, channel: 2, sub_channel: 3, plat: 4 },
        CopyProgressEntity: { id: 1, userId: 2, pCopyId: 3, pTime: 4, copyArr: 5, timeArr: 6, copyStar: 7, resetCounts: 8, timesPerDay: 9, finished: 10, refreshTime: 11 },
        CouponEntity: { id: 1, userId: 2, name: 3, content: 4, code: 5, type: 6, startTime: 7, endTime: 8, items: 9, channel: 10, isUsed: 11 },
        EquipEntity: { id: 1, userId: 2, heroId: 3, part: 4, tempId: 5, lvl: 6, exclusiveExp: 7 },
        ExchangeEntity: { id: 1, userId: 2, items: 3, dailyItems: 4, lastTime: 5, refreshTime: 6 },
        FeedbackEntity: { id: 1, userId: 2, feedContent: 3, feedTime: 4, replyId: 5, replyContent: 6, replayTime: 7 },
        GameConfigEntity: { id: 1, resUrl: 2, zipUrl: 3 },
        GameRecordEntity: { id: 1, loadRecord: 2 },
        GuildEntity: { id: 1, name: 2, icon: 3, lvl: 4, buildValue: 5, menberNum: 6 },
        GuildRankEntity: { id: 1, guildId: 2, guildName: 3, guildIcon: 4, guildLvl: 5, buildValue: 6, menberNum: 7 },
        HeroEntity: { id: 1, userId: 2, tempId: 3, tempTid: 4, pos: 5, posArenaD: 6, posArenaA: 7, posMirrorD: 8, posMirrorA: 9, posTower: 10, posTrial: 11, expc: 12, lvl: 13, trainLvl: 14, life: 15, power: 16, intel: 17, hp: 18, energy: 19, pAttack: 20, pDefence: 21, mAttack: 22, mDefence: 23, crit: 24, reCrit: 25, hit: 26, reHit: 27, pAttackMult: 28, pDefenceMult: 29, mAttackMult: 30, mDefenceMult: 31, suckBlood: 32, ignoreDefence: 33, normalSkill: 34, skills: 35, skillLvl: 36, mixSkill: 37, hpRecovery: 38, energyRecovery: 39, potentialTrain: 40, potentialUpdate: 41, combatEff: 42 },
        HeroRankEntity: { id: 1, userId: 2, userName: 3, heroId: 4, heroLvl: 5, heroTempId: 6, combatEff: 7 },
        LotteryEntity: { id: 1, userId: 2, goldTodayCount: 3, goldRefreshTime: 4, goldCount: 5, goldHistory: 6, goldCDOverTime: 7, diamondCount: 8, diamondHistory: 9, diamondCDOverTime: 10 },
        MailEntity: { id: 1, userId: 2, type: 3, fromName: 4, title: 5, content: 6, replaceArgs: 7, items: 8, isPicked: 9, isRead: 10, delHours: 11, delTime: 12, expireTime: 13, addTime: 14 },
        ManagerEntity: { id: 1, name: 2, pwd: 3, groupId: 4 },
        ManagerGroup: { id: 1, name: 2, rights: 3 },
        ManagerLoadLogEntity: { id: 1, count: 2, moduleId: 3, deviceId: 4, channelId: 5 },
        ManagerLog: { id: 1, managerId: 2, managerName: 3, module: 4, serverId: 5, type: 6, operation: 7, ip: 8, time: 9, tid: 10 },
        MirrorDefenceHistoryEntity: { id: 1, userId: 2, history: 3, count: 4, refreshTime: 5 },
        MirrorRankEntity: { id: 1, userId: 2, type: 3, enterTime: 4, isIn: 5, tids: 6, lockEndTime: 7 },
        MirrorRankViewEntity: { id: 1, userId: 2, type: 3, enterTime: 4, isIn: 5, tids: 6, lockEndTime: 7, name: 8, lvl: 9, iconId: 10, combatEff: 11, isLocked: 12, totalGain: 13 },
        NoticeEntity: { id: 1, title: 2, content: 3, serverId: 4, isOpen: 5, updateTime: 6 },
        RechargeEntity: { id: 1, userId: 2, rechargeId: 3, diamond: 4, rechargeTime: 5, effTime: 6, channelId: 7, transId: 8, currency: 9, ip: 10, payMoney: 11, userLvl: 12 },
        RechargeRequestEntity: { id: 1, accountId: 2, userId: 3, serverId: 4, rechargeId: 5, status: 6, addTime: 7, transId: 8 },
        ServerInfoEntity: { id: 1, name: 2, area: 3, host: 4, port: 5, isNew: 6, status: 7, dbLink: 8 },
        ShopEntity: { id: 1, userId: 2, items1: 3, lastTime1: 4, refreshCount1: 5, refreshCountResetTime1: 6, items2: 7, lastTime2: 8, refreshCount2: 9, refreshCountResetTime2: 10, disappearTime2: 11, appearCount2: 12, rateBeginTime2: 13, items3: 14, lastTime3: 15, refreshCount3: 16, refreshCountResetTime3: 17, disappearTime3: 18, appearCount3: 19, rateBeginTime3: 20, items4: 21, lastTime4: 22, refreshCount4: 23, refreshCountResetTime4: 24, items5: 25, lastTime5: 26, refreshCount5: 27, refreshCountResetTime5: 28 },
        TaskEntity: { id: 1, userId: 2, dailyTasks: 3, tasks: 4, refreshTime: 5, doneTasks: 6 },
        TowerEntity: { id: 1, userId: 2, reNum: 3, reTime: 4, layer: 5, highLayer: 6, highSpend: 7, startTime: 8, chestLayer: 9 },
        TowerRankEntity: { id: 1, userId: 2, userName: 3, userLvl: 4, userVip: 5, userIconId: 6, layer: 7, spend: 8 },
        UserEntity: { id: 1, name: 2, accountId: 3, lastLoginTime: 4, loginCount: 5, gold: 6, diamond: 7, give_diamond: 8, buy_diamond: 9, exploit: 10, towerPoints: 11, honor: 12, strength: 13, strengthReTime: 14, bag: 15, changeNameCount: 16, lvl: 17, expc: 18, iconId: 19, vip: 20, vipScore: 21, skillPointsReTime: 22, guide: 23, subGuide: 24, secret: 25, fightUnique: 26, counts: 27, countsRefreshTime: 28, sign: 29, activity: 30, serverId: 31, create_ip: 32, create_time: 33, last_map_1: 34, last_map_2: 35, coupon: 36, updateTime: 37, record: 38 },
        UserMirrorCombatViewEntity: { userId: 1, combatEff: 2 },
        UserRecordEntity: { id: 1, userId: 2, moduleId: 3 },
        FightResult: { rank: 1, star: 2, diamond: 3, chestItems: 4, wipeItems: 5, items: 6, heroes: 7, equips: 8, mirrorEnterState: 9 },
        ServerInfo: { id: 1, area: 2, name: 3, host: 4, port: 5, isNew: 6, status: 7 },
        CopyProgressState: { state: 1, star: 2, times: 3 },
        StrengthInfo: { strength: 1, buyCount: 2, nextReplyTime: 3, allReplayTime: 4 },
        SkillPointsInfo: { replyTime: 1, skillPoints: 2 },
        UseItemInfo: { items: 1, equips: 2, hero: 3, equipIdsToDel: 4 },
        inlayGem: { upGem: 1, downGem: 2 },
        gemItem: { id: 1, pos: 2 },
        ArenaInfo: { isNew: 1, arena: 2, fightUsers: 3 },
        ArenaFightUser: { id: 1, name: 2, lvl: 3, iconId: 4, rank: 5, combatEff: 6, heroes: 7 },
        Rank: { rank: 1, name: 2, lvl: 3, guildName: 4, layer: 5, iconId: 6 },
        ArenaLuckRank: { today: 1, yesterday: 2 },
        TaskReward: { task: 1, equips: 2 },
        HeroAndEquip: { hero: 1, equip: 2 },
        ArenaFight: { uniqueKey: 1, heroes: 2, secretSkills: 3, enemyUserId: 4 },
        RechargeData: { countMap: 1, cardTimeMap: 2 },
        SecretShopAppearData: { shopEntity: 1, shopFlag: 2 },
        ActivityData: { id: 1, title: 2, type: 3, iconType: 4, tiIconType: 5, startTime: 6, endTime: 7, items: 8, content: 9, isOpen: 10, todayRecharge: 11, allRecharge: 12, todayCost: 13, allCost: 14 },
        ActivityItem: { items: 1, diamond: 2, userLvl: 3, limitNum: 4, heroTempId: 5 },
        LoginData: { sdkData: 1, account: 2 },
        SDKData: { id: 1, name: 2 }
    };
})(uw || (uw = {}));
