var res;
(function (res) {
    var ui_arena;
    (function (ui_arena) {
        ui_arena.blk_ranknumcooper_png = "ui_arena#blk_ranknumcooper.png";
        ui_arena.blk_ranknumgold_png = "ui_arena#blk_ranknumgold.png";
        ui_arena.blk_ranknumnormal_png = "ui_arena#blk_ranknumnormal.png";
        ui_arena.blk_ranktiltle_png = "ui_arena#blk_ranktiltle.png";
        ui_arena.blk_redstrip_png = "ui_arena#blk_redstrip.png";
        ui_arena.btn_battlerecord_png = "ui_arena#btn_battlerecord.png";
        ui_arena.btn_changechallenger_png = "ui_arena#btn_changechallenger.png";
        ui_arena.btn_exchange_png = "ui_arena#btn_exchange.png";
        ui_arena.btn_luckyrank_png = "ui_arena#btn_luckyrank.png";
        ui_arena.btn_rank_png = "ui_arena#btn_rank.png";
        ui_arena.btn_timet_png = "ui_arena#btn_timet.png";
        ui_arena.cov_head_png = "ui_arena#cov_head.png";
        ui_arena.gezihong1_png = "ui_arena#gezihong1.png";
        ui_arena.ntc_blkfigurel_png = "ui_arena#ntc_blkfigurel.png";
        ui_arena.ntc_blkfigurer_png = "ui_arena#ntc_blkfigurer.png";
        ui_arena.ntc_luckrank_png = "ui_arena#ntc_luckrank.png";
        ui_arena.num_r0_png = "ui_arena#num_r0.png";
        ui_arena.num_r1_png = "ui_arena#num_r1.png";
        ui_arena.num_r2_png = "ui_arena#num_r2.png";
        ui_arena.num_r3_png = "ui_arena#num_r3.png";
        ui_arena.num_r4_png = "ui_arena#num_r4.png";
        ui_arena.num_r5_png = "ui_arena#num_r5.png";
        ui_arena.num_r6_png = "ui_arena#num_r6.png";
        ui_arena.num_r7_png = "ui_arena#num_r7.png";
        ui_arena.num_r8_png = "ui_arena#num_r8.png";
        ui_arena.num_r9_png = "ui_arena#num_r9.png";
        ui_arena.num_rank0_png = "ui_arena#num_rank0.png";
        ui_arena.num_rank1_png = "ui_arena#num_rank1.png";
        ui_arena.num_rank2_png = "ui_arena#num_rank2.png";
        ui_arena.num_rank3_png = "ui_arena#num_rank3.png";
        ui_arena.num_rank4_png = "ui_arena#num_rank4.png";
        ui_arena.num_rank5_png = "ui_arena#num_rank5.png";
        ui_arena.num_rank6_png = "ui_arena#num_rank6.png";
        ui_arena.num_rank7_png = "ui_arena#num_rank7.png";
        ui_arena.num_rank8_png = "ui_arena#num_rank8.png";
        ui_arena.num_rank9_png = "ui_arena#num_rank9.png";
    })(ui_arena = res.ui_arena || (res.ui_arena = {}));
})(res || (res = {}));
var res;
(function (res) {
    var ui_bag;
    (function (ui_bag) {
        ui_bag.blk_numbers_png = "ui_bag#blk_numbers.png";
        ui_bag.blk_numbersS_png = "ui_bag#blk_numbersS.png";
        ui_bag.blk_nums_png = "ui_bag#blk_nums.png";
        ui_bag.minus_png = "ui_bag#minus.png";
        ui_bag.plus_png = "ui_bag#plus.png";
        ui_bag.sale_max_png = "ui_bag#sale_max.png";
    })(ui_bag = res.ui_bag || (res.ui_bag = {}));
})(res || (res = {}));
var res;
(function (res) {
    var ui_bg;
    (function (ui_bg) {
        ui_bg.bg_arane_jpg = "ui/ui_bg/bg_arane.jpg";
        ui_bg.bg_bag_jpg = "ui/ui_bg/bg_bag.jpg";
        ui_bg.bg_copy_mi_jpg = "ui/ui_bg/bg_copy_mi.jpg";
        ui_bg.bg_equipment_jpg = "ui/ui_bg/bg_equipment.jpg";
        ui_bg.bg_film_jpg = "ui/ui_bg/bg_film.jpg";
        ui_bg.bg_getHero_jpg = "ui/ui_bg/bg_getHero.jpg";
        ui_bg.bg_heroform_jpg = "ui/ui_bg/bg_heroform.jpg";
        ui_bg.bg_home_jpg = "ui/ui_bg/bg_home.jpg";
        ui_bg.bg_lottery_jpg = "ui/ui_bg/bg_lottery.jpg";
        ui_bg.bg_midlight_png = "ui/ui_bg/bg_midlight.png";
        ui_bg.bg_mirrorworld_jpg = "ui/ui_bg/bg_mirrorworld.jpg";
        ui_bg.bg_tower_jpg = "ui/ui_bg/bg_tower.jpg";
        ui_bg.bg_trial_jpg = "ui/ui_bg/bg_trial.jpg";
        ui_bg.contrantbg_jpg = "ui/ui_bg/contrantbg.jpg";
        ui_bg.login_jpg = "ui/ui_bg/login.jpg";
    })(ui_bg = res.ui_bg || (res.ui_bg = {}));
})(res || (res = {}));
var res;
(function (res) {
    var ui_btn;
    (function (ui_btn) {
        ui_btn.btn_10more_png = "ui_btn#btn_10more.png";
        ui_btn.btn_add_png = "ui_btn#btn_add.png";
        ui_btn.btn_adjust_png = "ui_btn#btn_adjust.png";
        ui_btn.btn_autowash_png = "ui_btn#btn_autowash.png";
        ui_btn.btn_back_png = "ui_btn#btn_back.png";
        ui_btn.btn_beginwashin_png = "ui_btn#btn_beginwashin.png";
        ui_btn.btn_cancel_png = "ui_btn#btn_cancel.png";
        ui_btn.btn_challenge_png = "ui_btn#btn_challenge.png";
        ui_btn.btn_changeEquip_png = "ui_btn#btn_changeEquip.png";
        ui_btn.btn_charge_png = "ui_btn#btn_charge.png";
        ui_btn.btn_check_png = "ui_btn#btn_check.png";
        ui_btn.btn_commix_png = "ui_btn#btn_commix.png";
        ui_btn.btn_confirm_png = "ui_btn#btn_confirm.png";
        ui_btn.btn_confirmblank_png = "ui_btn#btn_confirmblank.png";
        ui_btn.btn_defencerecord_png = "ui_btn#btn_defencerecord.png";
        ui_btn.btn_detail_png = "ui_btn#btn_detail.png";
        ui_btn.btn_evolution_png = "ui_btn#btn_evolution.png";
        ui_btn.btn_exchange_png = "ui_btn#btn_exchange.png";
        ui_btn.btn_extract_png = "ui_btn#btn_extract.png";
        ui_btn.btn_f5_png = "ui_btn#btn_f5.png";
        ui_btn.btn_fallback_png = "ui_btn#btn_fallback.png";
        ui_btn.btn_formation_png = "ui_btn#btn_formation.png";
        ui_btn.btn_get_png = "ui_btn#btn_get.png";
        ui_btn.btn_goto_png = "ui_btn#btn_goto.png";
        ui_btn.btn_inlay_png = "ui_btn#btn_inlay.png";
        ui_btn.btn_inter_png = "ui_btn#btn_inter.png";
        ui_btn.btn_mixture_png = "ui_btn#btn_mixture.png";
        ui_btn.btn_mixtureOneOper_png = "ui_btn#btn_mixtureOneOper.png";
        ui_btn.btn_mulityuse_png = "ui_btn#btn_mulityuse.png";
        ui_btn.btn_nmore_png = "ui_btn#btn_nmore.png";
        ui_btn.btn_purchase_png = "ui_btn#btn_purchase.png";
        ui_btn.btn_putOff_png = "ui_btn#btn_putOff.png";
        ui_btn.btn_putOn_png = "ui_btn#btn_putOn.png";
        ui_btn.btn_replay_png = "ui_btn#btn_replay.png";
        ui_btn.btn_reset_png = "ui_btn#btn_reset.png";
        ui_btn.btn_retry_png = "ui_btn#btn_retry.png";
        ui_btn.btn_sale_png = "ui_btn#btn_sale.png";
        ui_btn.btn_save_png = "ui_btn#btn_save.png";
        ui_btn.btn_send_png = "ui_btn#btn_send.png";
        ui_btn.btn_share_png = "ui_btn#btn_share.png";
        ui_btn.btn_sommon_png = "ui_btn#btn_sommon.png";
        ui_btn.btn_sommononemore_png = "ui_btn#btn_sommononemore.png";
        ui_btn.btn_sommontentimes_png = "ui_btn#btn_sommontentimes.png";
        ui_btn.btn_takeway_png = "ui_btn#btn_takeway.png";
        ui_btn.btn_train_png = "ui_btn#btn_train.png";
        ui_btn.btn_treasure_png = "ui_btn#btn_treasure.png";
        ui_btn.btn_use_png = "ui_btn#btn_use.png";
        ui_btn.btn_vipPrivilege_png = "ui_btn#btn_vipPrivilege.png";
        ui_btn.btn_wash_png = "ui_btn#btn_wash.png";
        ui_btn.cream_png = "ui_btn#cream.png";
        ui_btn.ico_forplus_png = "ui_btn#ico_forplus.png";
        ui_btn.ico_forpluslocked_png = "ui_btn#ico_forpluslocked.png";
        ui_btn.lock_png = "ui_btn#lock.png";
        ui_btn.normal_png = "ui_btn#normal.png";
        ui_btn.trial_png = "ui_btn#trial.png";
    })(ui_btn = res.ui_btn || (res.ui_btn = {}));
})(res || (res = {}));
var res;
(function (res) {
    var ui_common;
    (function (ui_common) {
        ui_common.bar1_png = "ui_common#bar1.png";
        ui_common.bar2_png = "ui_common#bar2.png";
        ui_common.bar3_png = "ui_common#bar3.png";
        ui_common.bar4_png = "ui_common#bar4.png";
        ui_common.bar_light1_png = "ui_common#bar_light1.png";
        ui_common.bar_light2_png = "ui_common#bar_light2.png";
        ui_common.bar_light4_png = "ui_common#bar_light4.png";
        ui_common.bar_loadinglight_png = "ui_common#bar_loadinglight.png";
        ui_common.bar_loadingtank_png = "ui_common#bar_loadingtank.png";
        ui_common.bar_vip2_png = "ui_common#bar_vip2.png";
        ui_common.bgformixture_png = "ui_common#bgformixture.png";
        ui_common.blk9_ntc_png = "ui_common#blk9_ntc.png";
        ui_common.blk9_q_0_png = "ui_common#blk9_q_0.png";
        ui_common.blk9_q_1_png = "ui_common#blk9_q_1.png";
        ui_common.blk9_q_2_png = "ui_common#blk9_q_2.png";
        ui_common.blk_boxtype_png = "ui_common#blk_boxtype.png";
        ui_common.blk_grain_png = "ui_common#blk_grain.png";
        ui_common.blk_headlevel_png = "ui_common#blk_headlevel.png";
        ui_common.blk_item_num_png = "ui_common#blk_item_num.png";
        ui_common.blk_jb_png = "ui_common#blk_jb.png";
        ui_common.blk_ntc_circle_png = "ui_common#blk_ntc_circle.png";
        ui_common.blk_skillint_png = "ui_common#blk_skillint.png";
        ui_common.blk_skillpas_png = "ui_common#blk_skillpas.png";
        ui_common.blk_skillunder_png = "ui_common#blk_skillunder.png";
        ui_common.blk_skillundero_png = "ui_common#blk_skillundero.png";
        ui_common.btn_arrow_png = "ui_common#btn_arrow.png";
        ui_common.btn_embattle_png = "ui_common#btn_embattle.png";
        ui_common.btn_new_png = "ui_common#btn_new.png";
        ui_common.btn_next2_png = "ui_common#btn_next2.png";
        ui_common.btn_pickme_png = "ui_common#btn_pickme.png";
        ui_common.btn_save_png = "ui_common#btn_save.png";
        ui_common.btn_select_png = "ui_common#btn_select.png";
        ui_common.clicktocontinue_png = "ui_common#clicktocontinue.png";
        ui_common.common_white_line_png = "ui_common#common_white_line.png";
        ui_common.copy_btn_boss02_png = "ui_common#copy_btn_boss02.png";
        ui_common.copy_btn_childbig02_png = "ui_common#copy_btn_childbig02.png";
        ui_common.copy_btn_childsmall03_png = "ui_common#copy_btn_childsmall03.png";
        ui_common.copy_choose_png = "ui_common#copy_choose.png";
        ui_common.copy_starformap_png = "ui_common#copy_starformap.png";
        ui_common.cov_lotteryitem_png = "ui_common#cov_lotteryitem.png";
        ui_common.dice_png = "ui_common#dice.png";
        ui_common.down_png = "ui_common#down.png";
        ui_common.greenlantun_png = "ui_common#greenlantun.png";
        ui_common.home_head_mark_png = "ui_common#home_head_mark.png";
        ui_common.ico_arw_png = "ui_common#ico_arw.png";
        ui_common.ico_choose_png = "ui_common#ico_choose.png";
        ui_common.ico_chooseBg_png = "ui_common#ico_chooseBg.png";
        ui_common.ico_diamond_png = "ui_common#ico_diamond.png";
        ui_common.ico_diamondplus_png = "ui_common#ico_diamondplus.png";
        ui_common.ico_gold_png = "ui_common#ico_gold.png";
        ui_common.ico_goldplus_png = "ui_common#ico_goldplus.png";
        ui_common.ico_honor_png = "ui_common#ico_honor.png";
        ui_common.ico_royalcoin_png = "ui_common#ico_royalcoin.png";
        ui_common.ico_royalpass_png = "ui_common#ico_royalpass.png";
        ui_common.ico_strength_png = "ui_common#ico_strength.png";
        ui_common.ico_strengthplus_png = "ui_common#ico_strengthplus.png";
        ui_common.ico_sweeping_png = "ui_common#ico_sweeping.png";
        ui_common.ico_trialcard_png = "ui_common#ico_trialcard.png";
        ui_common.img_default_png = "ui_common#img_default.png";
        ui_common.light_png = "ui_common#light.png";
        ui_common.light1_png = "ui_common#light1.png";
        ui_common.lightTask_png = "ui_common#lightTask.png";
        ui_common.logo_loading_png = "ui_common#logo_loading.png";
        ui_common.ntc_inborad_png = "ui_common#ntc_inborad.png";
        ui_common.ntc_levelup_png = "ui_common#ntc_levelup.png";
        ui_common.ntc_loading_png = "ui_common#ntc_loading.png";
        ui_common.ntc_norandomskillsw_png = "ui_common#ntc_norandomskillsw.png";
        ui_common.ntc_norecord_png = "ui_common#ntc_norecord.png";
        ui_common.ntc_pieces_png = "ui_common#ntc_pieces.png";
        ui_common.ntc_soulpieces_png = "ui_common#ntc_soulpieces.png";
        ui_common.shadow_png = "ui_common#shadow.png";
        ui_common.tag_focus2_png = "ui_common#tag_focus2.png";
        ui_common.tg_png = "ui_common#tg.png";
        ui_common.up_png = "ui_common#up.png";
    })(ui_common = res.ui_common || (res.ui_common = {}));
})(res || (res = {}));
var res;
(function (res) {
    var ui_copy;
    (function (ui_copy) {
        ui_copy.AoSiDunZhiCheng_png = "ui_copy#AoSiDunZhiCheng.png";
        ui_copy.AoSiDunZhiChengWaiFaGuang_png = "ui_copy#AoSiDunZhiChengWaiFaGuang.png";
        ui_copy.AoSiDunZhiChengWeiJieSuo_png = "ui_copy#AoSiDunZhiChengWeiJieSuo.png";
        ui_copy.baofengzhiyandianji_png = "ui_copy#baofengzhiyandianji.png";
        ui_copy.baofengzhiyanweijiesuo_png = "ui_copy#baofengzhiyanweijiesuo.png";
        ui_copy.baofengzhiyanyijiesuo_png = "ui_copy#baofengzhiyanyijiesuo.png";
        ui_copy.beifengyaosaidianji_png = "ui_copy#beifengyaosaidianji.png";
        ui_copy.beifengyaosaiweijiesuo_png = "ui_copy#beifengyaosaiweijiesuo.png";
        ui_copy.beifengyaosaiyijiesuo_png = "ui_copy#beifengyaosaiyijiesuo.png";
        ui_copy.BeiJing_png = "ui_copy#BeiJing.png";
        ui_copy.copy_bg_typebar_png = "ui_copy#copy_bg_typebar.png";
        ui_copy.copy_btn_normaltype01_png = "ui_copy#copy_btn_normaltype01.png";
        ui_copy.copy_btn_normaltype02_png = "ui_copy#copy_btn_normaltype02.png";
        ui_copy.copy_btn_protype01_png = "ui_copy#copy_btn_protype01.png";
        ui_copy.copy_btn_protype02_png = "ui_copy#copy_btn_protype02.png";
        ui_copy.copy_btn_stage01_png = "ui_copy#copy_btn_stage01.png";
        ui_copy.copy_btn_stage02_png = "ui_copy#copy_btn_stage02.png";
        ui_copy.copy_icon_connect_png = "ui_copy#copy_icon_connect.png";
        ui_copy.copy_map_child_level0_jpg = "ui_copy#copy_map_child_level0.jpg";
        ui_copy.copy_map_child_level0_elite_jpg = "ui_copy#copy_map_child_level0_elite.jpg";
        ui_copy.copy_map_midcornerL_png = "ui_copy#copy_map_midcornerL.png";
        ui_copy.copy_map_midcornerline_png = "ui_copy#copy_map_midcornerline.png";
        ui_copy.copy_map_midcornerlineblue_png = "ui_copy#copy_map_midcornerlineblue.png";
        ui_copy.copy_map_midcornerpattern_png = "ui_copy#copy_map_midcornerpattern.png";
        ui_copy.copy_map_midcornerR_png = "ui_copy#copy_map_midcornerR.png";
        ui_copy.copy_ntc_circle_png = "ui_copy#copy_ntc_circle.png";
        ui_copy.DiLaKeOuLa_png = "ui_copy#DiLaKeOuLa.png";
        ui_copy.DiLaKeOuLaWaiFaGuang_png = "ui_copy#DiLaKeOuLaWaiFaGuang.png";
        ui_copy.DiLaKeOuLaWeiJieSuo_png = "ui_copy#DiLaKeOuLaWeiJieSuo.png";
        ui_copy.dimiana_png = "ui_copy#dimiana.png";
        ui_copy.dimianb_png = "ui_copy#dimianb.png";
        ui_copy.emotingyuandianji_png = "ui_copy#emotingyuandianji.png";
        ui_copy.emotingyuanweijiesuo_png = "ui_copy#emotingyuanweijiesuo.png";
        ui_copy.emotingyuanyijiesuo_png = "ui_copy#emotingyuanyijiesuo.png";
        ui_copy.heianzhimendianji_png = "ui_copy#heianzhimendianji.png";
        ui_copy.heianzhimenweijiesuo_png = "ui_copy#heianzhimenweijiesuo.png";
        ui_copy.heianzhimenyijiesuo_png = "ui_copy#heianzhimenyijiesuo.png";
        ui_copy.HouYunCengPinJieB_png = "ui_copy#HouYunCengPinJieB.png";
        ui_copy.HouYunYengPinJieA_png = "ui_copy#HouYunYengPinJieA.png";
        ui_copy.KongJuFeiTu_png = "ui_copy#KongJuFeiTu.png";
        ui_copy.KongJuFeiTuWaiFaGuang_png = "ui_copy#KongJuFeiTuWaiFaGuang.png";
        ui_copy.KongJuFeiTuWeiJieSuo_png = "ui_copy#KongJuFeiTuWeiJieSuo.png";
        ui_copy.longrenlingdidianji_png = "ui_copy#longrenlingdidianji.png";
        ui_copy.longrenlingdiyijiesuo_png = "ui_copy#longrenlingdiyijiesuo.png";
        ui_copy.longrenlingweikaiqi_png = "ui_copy#longrenlingweikaiqi.png";
        ui_copy.MiShiZhiJing_png = "ui_copy#MiShiZhiJing.png";
        ui_copy.MiShiZhiJingWaiFaGuang_png = "ui_copy#MiShiZhiJingWaiFaGuang.png";
        ui_copy.MiShiZhiJingWeiJieSuo_png = "ui_copy#MiShiZhiJingWeiJieSuo.png";
        ui_copy.ntc_locked_png = "ui_copy#ntc_locked.png";
        ui_copy.QianJing_png = "ui_copy#QianJing.png";
        ui_copy.shiluozhichengdianji_png = "ui_copy#shiluozhichengdianji.png";
        ui_copy.shiluozhichengweijiesuo_png = "ui_copy#shiluozhichengweijiesuo.png";
        ui_copy.shiluozhichengyijiesuo_png = "ui_copy#shiluozhichengyijiesuo.png";
        ui_copy.TieXueWangZuo_png = "ui_copy#TieXueWangZuo.png";
        ui_copy.TieXueWangZuoWaiFaGuang_png = "ui_copy#TieXueWangZuoWaiFaGuang.png";
        ui_copy.TieXueWangZuoWeiJieSuo_png = "ui_copy#TieXueWangZuoWeiJieSuo.png";
        ui_copy.TongKuZhanChang_png = "ui_copy#TongKuZhanChang.png";
        ui_copy.TongKuZhanChangWaiFaGuang_png = "ui_copy#TongKuZhanChangWaiFaGuang.png";
        ui_copy.TongKuZhanChangWeiJieSuo_png = "ui_copy#TongKuZhanChangWeiJieSuo.png";
        ui_copy.xuwangkongjiandianji_png = "ui_copy#xuwangkongjiandianji.png";
        ui_copy.xuwangkongjianweijiesuo_png = "ui_copy#xuwangkongjianweijiesuo.png";
        ui_copy.xuwangkongjianyijiesuo_png = "ui_copy#xuwangkongjianyijiesuo.png";
        ui_copy.YunDuoA_png = "ui_copy#YunDuoA.png";
        ui_copy.YunDuoB_png = "ui_copy#YunDuoB.png";
        ui_copy.YunDuoC_png = "ui_copy#YunDuoC.png";
        ui_copy.YunDuoD_png = "ui_copy#YunDuoD.png";
        ui_copy.ZuZhouZhiGu_png = "ui_copy#ZuZhouZhiGu.png";
        ui_copy.ZuZhouZhiGuWaiFaGuang_png = "ui_copy#ZuZhouZhiGuWaiFaGuang.png";
        ui_copy.ZuZhouZhiGuWeiJieSuo_png = "ui_copy#ZuZhouZhiGuWeiJieSuo.png";
    })(ui_copy = res.ui_copy || (res.ui_copy = {}));
})(res || (res = {}));
var res;
(function (res) {
    var ui_copyInfo;
    (function (ui_copyInfo) {
        ui_copyInfo.btn_purchase_png = "ui_copyInfo#btn_purchase.png";
        ui_copyInfo.copy_btn_continue_png = "ui_copyInfo#copy_btn_continue.png";
        ui_copyInfo.copy_btn_noraids_png = "ui_copyInfo#copy_btn_noraids.png";
        ui_copyInfo.copy_btn_raids_png = "ui_copyInfo#copy_btn_raids.png";
        ui_copyInfo.copy_btn_raids1_png = "ui_copyInfo#copy_btn_raids1.png";
        ui_copyInfo.copy_star_png = "ui_copyInfo#copy_star.png";
        ui_copyInfo.copy_star_gray_png = "ui_copyInfo#copy_star_gray.png";
        ui_copyInfo.copy_under_stars_png = "ui_copyInfo#copy_under_stars.png";
        ui_copyInfo.raids_under_vipbouns_png = "ui_copyInfo#raids_under_vipbouns.png";
        ui_copyInfo.raids_vipbouns_png = "ui_copyInfo#raids_vipbouns.png";
        ui_copyInfo.redcorner_png = "ui_copyInfo#redcorner.png";
    })(ui_copyInfo = res.ui_copyInfo || (res.ui_copyInfo = {}));
})(res || (res = {}));
var res;
(function (res) {
    var ui_daily;
    (function (ui_daily) {
        ui_daily.blk_item_png = "ui_daily#blk_item.png";
        ui_daily.cov_recived_png = "ui_daily#cov_recived.png";
        ui_daily.ntc_corrnerstrip_png = "ui_daily#ntc_corrnerstrip.png";
        ui_daily.ntc_double_png = "ui_daily#ntc_double.png";
        ui_daily.ntc_fillsign_png = "ui_daily#ntc_fillsign.png";
        ui_daily.und_todays_png = "ui_daily#und_todays.png";
        ui_daily.wrd_v1_png = "ui_daily#wrd_v1.png";
        ui_daily.wrd_v10_png = "ui_daily#wrd_v10.png";
        ui_daily.wrd_v11_png = "ui_daily#wrd_v11.png";
        ui_daily.wrd_v12_png = "ui_daily#wrd_v12.png";
        ui_daily.wrd_v13_png = "ui_daily#wrd_v13.png";
        ui_daily.wrd_v14_png = "ui_daily#wrd_v14.png";
        ui_daily.wrd_v15_png = "ui_daily#wrd_v15.png";
        ui_daily.wrd_v16_png = "ui_daily#wrd_v16.png";
        ui_daily.wrd_v2_png = "ui_daily#wrd_v2.png";
        ui_daily.wrd_v3_png = "ui_daily#wrd_v3.png";
        ui_daily.wrd_v4_png = "ui_daily#wrd_v4.png";
        ui_daily.wrd_v5_png = "ui_daily#wrd_v5.png";
        ui_daily.wrd_v6_png = "ui_daily#wrd_v6.png";
        ui_daily.wrd_v7_png = "ui_daily#wrd_v7.png";
        ui_daily.wrd_v8_png = "ui_daily#wrd_v8.png";
        ui_daily.wrd_v9_png = "ui_daily#wrd_v9.png";
    })(ui_daily = res.ui_daily || (res.ui_daily = {}));
})(res || (res = {}));
var res;
(function (res) {
    var ui_embattle;
    (function (ui_embattle) {
        ui_embattle.blk_redskills_png = "ui_embattle#blk_redskills.png";
        ui_embattle.blk_redskills2new_png = "ui_embattle#blk_redskills2new.png";
        ui_embattle.blk_redunder_png = "ui_embattle#blk_redunder.png";
        ui_embattle.copy_buzhen_png = "ui_embattle#copy_buzhen.png";
        ui_embattle.copy_dibang_png = "ui_embattle#copy_dibang.png";
        ui_embattle.copy_gezihong1_png = "ui_embattle#copy_gezihong1.png";
        ui_embattle.copy_lang_png = "ui_embattle#copy_lang.png";
        ui_embattle.copy_under_raids_png = "ui_embattle#copy_under_raids.png";
        ui_embattle.copy_xian_png = "ui_embattle#copy_xian.png";
        ui_embattle.pat_battle_png = "ui_embattle#pat_battle.png";
        ui_embattle.pat_power_png = "ui_embattle#pat_power.png";
    })(ui_embattle = res.ui_embattle || (res.ui_embattle = {}));
})(res || (res = {}));
var res;
(function (res) {
    var ui_equipment;
    (function (ui_equipment) {
        ui_equipment.blk_exclusive_png = "ui_equipment#blk_exclusive.png";
        ui_equipment.blk_gemmounting_png = "ui_equipment#blk_gemmounting.png";
        ui_equipment.btn_changgehero_png = "ui_equipment#btn_changgehero.png";
        ui_equipment.btn_choosehero_png = "ui_equipment#btn_choosehero.png";
        ui_equipment.btn_rule_png = "ui_equipment#btn_rule.png";
        ui_equipment.btn_rule_unfocus_png = "ui_equipment#btn_rule_unfocus.png";
    })(ui_equipment = res.ui_equipment || (res.ui_equipment = {}));
})(res || (res = {}));
var res;
(function (res) {
    var ui_event;
    (function (ui_event) {
        ui_event.blk9_forcg_png = "ui_event#blk9_forcg.png";
        ui_event.blk_giftitem_png = "ui_event#blk_giftitem.png";
        ui_event.blk_input_png = "ui_event#blk_input.png";
        ui_event.btn_buy1_png = "ui_event#btn_buy1.png";
        ui_event.btn_getmemoney_png = "ui_event#btn_getmemoney.png";
        ui_event.btn_getshit_png = "ui_event#btn_getshit.png";
        ui_event.btn_plusgift_png = "ui_event#btn_plusgift.png";
        ui_event.corner_goldblk_png = "ui_event#corner_goldblk.png";
        ui_event.icon_png = "ui_event#icon.png";
        ui_event.ntc_cg2_jpg = "ui_event#ntc_cg2.jpg";
        ui_event.ntc_cg7_jpg = "ui_event#ntc_cg7.jpg";
        ui_event.ntc_cgcode_jpg = "ui_event#ntc_cgcode.jpg";
        ui_event.ntc_day_png = "ui_event#ntc_day.png";
        ui_event.ntc_firsttopup_png = "ui_event#ntc_firsttopup.png";
        ui_event.ntc_gotit_png = "ui_event#ntc_gotit.png";
        ui_event.ntc_soldout_png = "ui_event#ntc_soldout.png";
        ui_event.ntc_titleinfo_png = "ui_event#ntc_titleinfo.png";
        ui_event.tag_27_png = "ui_event#tag_27.png";
        ui_event.tag_7ds_png = "ui_event#tag_7ds.png";
        ui_event.tag_eventfocus_png = "ui_event#tag_eventfocus.png";
        ui_event.tag_eventunfocus_png = "ui_event#tag_eventunfocus.png";
        ui_event.tag_focus_png = "ui_event#tag_focus.png";
        ui_event.tit_7ds_png = "ui_event#tit_7ds.png";
        ui_event.tit_blubond_png = "ui_event#tit_blubond.png";
        ui_event.tit_redbond_png = "ui_event#tit_redbond.png";
        ui_event.tit_type1_png = "ui_event#tit_type1.png";
        ui_event.tit_type2_png = "ui_event#tit_type2.png";
        ui_event.tit_type3_png = "ui_event#tit_type3.png";
        ui_event.tit_type4_png = "ui_event#tit_type4.png";
        ui_event.tit_type5_png = "ui_event#tit_type5.png";
        ui_event.tit_type6_png = "ui_event#tit_type6.png";
        ui_event.tit_type7_png = "ui_event#tit_type7.png";
        ui_event.tit_type8_png = "ui_event#tit_type8.png";
        ui_event.tit_type9_png = "ui_event#tit_type9.png";
        ui_event.wrd_2rdd_png = "ui_event#wrd_2rdd.png";
        ui_event.wrd_2rdd_focus_png = "ui_event#wrd_2rdd_focus.png";
        ui_event.wrd_7thd_png = "ui_event#wrd_7thd.png";
        ui_event.wrd_7thd_focus_png = "ui_event#wrd_7thd_focus.png";
        ui_event.wrd_type1_png = "ui_event#wrd_type1.png";
        ui_event.wrd_type2_png = "ui_event#wrd_type2.png";
        ui_event.wrd_type3_png = "ui_event#wrd_type3.png";
        ui_event.wrd_type4_png = "ui_event#wrd_type4.png";
        ui_event.wrd_type5_png = "ui_event#wrd_type5.png";
    })(ui_event = res.ui_event || (res.ui_event = {}));
})(res || (res = {}));
var res;
(function (res) {
    var ui_feedback;
    (function (ui_feedback) {
        ui_feedback.blk9_input_png = "ui_feedback#blk9_input.png";
        ui_feedback.blk_title_png = "ui_feedback#blk_title.png";
        ui_feedback.btn_submit_png = "ui_feedback#btn_submit.png";
        ui_feedback.line_b_png = "ui_feedback#line_b.png";
    })(ui_feedback = res.ui_feedback || (res.ui_feedback = {}));
})(res || (res = {}));
var res;
(function (res) {
    var ui_fight;
    (function (ui_fight) {
        ui_fight.bar_hpennew_png = "ui_fight#bar_hpennew.png";
        ui_fight.battlestatus_under_png = "ui_fight#battlestatus_under.png";
        ui_fight.blk_hermeticblank_png = "ui_fight#blk_hermeticblank.png";
        ui_fight.blk_hp_png = "ui_fight#blk_hp.png";
        ui_fight.blk_lose_png = "ui_fight#blk_lose.png";
        ui_fight.blk_openinglk_png = "ui_fight#blk_openinglk.png";
        ui_fight.blk_skill1_png = "ui_fight#blk_skill1.png";
        ui_fight.blk_skill1_unable_png = "ui_fight#blk_skill1_unable.png";
        ui_fight.blk_skill2_png = "ui_fight#blk_skill2.png";
        ui_fight.blk_skill2_unable_png = "ui_fight#blk_skill2_unable.png";
        ui_fight.blk_skillunder_png = "ui_fight#blk_skillunder.png";
        ui_fight.blk_timer_png = "ui_fight#blk_timer.png";
        ui_fight.blk_win_png = "ui_fight#blk_win.png";
        ui_fight.btn_auto_off_png = "ui_fight#btn_auto_off.png";
        ui_fight.btn_auto_on_png = "ui_fight#btn_auto_on.png";
        ui_fight.btn_continue_png = "ui_fight#btn_continue.png";
        ui_fight.btn_pause_png = "ui_fight#btn_pause.png";
        ui_fight.btn_pause_focus_png = "ui_fight#btn_pause_focus.png";
        ui_fight.btn_quit_png = "ui_fight#btn_quit.png";
        ui_fight.btn_replay_png = "ui_fight#btn_replay.png";
        ui_fight.btn_resume_png = "ui_fight#btn_resume.png";
        ui_fight.btn_soundoff_png = "ui_fight#btn_soundoff.png";
        ui_fight.btn_soundon_png = "ui_fight#btn_soundon.png";
        ui_fight.cov_redflo_png = "ui_fight#cov_redflo.png";
        ui_fight.exp01_png = "ui_fight#exp01.png";
        ui_fight.exp02_png = "ui_fight#exp02.png";
        ui_fight.exp03_png = "ui_fight#exp03.png";
        ui_fight.exp_hero_png = "ui_fight#exp_hero.png";
        ui_fight.fight_buff_blood_0_png = "ui_fight#fight_buff_blood_0.png";
        ui_fight.fight_buff_blood_1_png = "ui_fight#fight_buff_blood_1.png";
        ui_fight.fight_buff_blood_2_png = "ui_fight#fight_buff_blood_2.png";
        ui_fight.fight_buff_blood_3_png = "ui_fight#fight_buff_blood_3.png";
        ui_fight.fight_buff_blood_4_png = "ui_fight#fight_buff_blood_4.png";
        ui_fight.fight_buff_blood_5_png = "ui_fight#fight_buff_blood_5.png";
        ui_fight.fight_buff_blood_6_png = "ui_fight#fight_buff_blood_6.png";
        ui_fight.fight_buff_blood_7_png = "ui_fight#fight_buff_blood_7.png";
        ui_fight.fight_buff_blood_8_png = "ui_fight#fight_buff_blood_8.png";
        ui_fight.fight_buff_blood_9_png = "ui_fight#fight_buff_blood_9.png";
        ui_fight.fight_buff_blood_plus_png = "ui_fight#fight_buff_blood_plus.png";
        ui_fight.fight_debuff_blood_0_png = "ui_fight#fight_debuff_blood_0.png";
        ui_fight.fight_debuff_blood_1_png = "ui_fight#fight_debuff_blood_1.png";
        ui_fight.fight_debuff_blood_2_png = "ui_fight#fight_debuff_blood_2.png";
        ui_fight.fight_debuff_blood_3_png = "ui_fight#fight_debuff_blood_3.png";
        ui_fight.fight_debuff_blood_4_png = "ui_fight#fight_debuff_blood_4.png";
        ui_fight.fight_debuff_blood_5_png = "ui_fight#fight_debuff_blood_5.png";
        ui_fight.fight_debuff_blood_6_png = "ui_fight#fight_debuff_blood_6.png";
        ui_fight.fight_debuff_blood_7_png = "ui_fight#fight_debuff_blood_7.png";
        ui_fight.fight_debuff_blood_8_png = "ui_fight#fight_debuff_blood_8.png";
        ui_fight.fight_debuff_blood_9_png = "ui_fight#fight_debuff_blood_9.png";
        ui_fight.fight_debuff_blood_minus_png = "ui_fight#fight_debuff_blood_minus.png";
        ui_fight.fight_energy_0_png = "ui_fight#fight_energy_0.png";
        ui_fight.fight_energy_1_png = "ui_fight#fight_energy_1.png";
        ui_fight.fight_energy_2_png = "ui_fight#fight_energy_2.png";
        ui_fight.fight_energy_3_png = "ui_fight#fight_energy_3.png";
        ui_fight.fight_energy_4_png = "ui_fight#fight_energy_4.png";
        ui_fight.fight_energy_5_png = "ui_fight#fight_energy_5.png";
        ui_fight.fight_energy_6_png = "ui_fight#fight_energy_6.png";
        ui_fight.fight_energy_7_png = "ui_fight#fight_energy_7.png";
        ui_fight.fight_energy_8_png = "ui_fight#fight_energy_8.png";
        ui_fight.fight_energy_9_png = "ui_fight#fight_energy_9.png";
        ui_fight.fight_energy_plus_png = "ui_fight#fight_energy_plus.png";
        ui_fight.fight_txt_aback_png = "ui_fight#fight_txt_aback.png";
        ui_fight.fight_txt_addEnergy_png = "ui_fight#fight_txt_addEnergy.png";
        ui_fight.fight_txt_armorbroke_png = "ui_fight#fight_txt_armorbroke.png";
        ui_fight.fight_txt_attackSpeedIncrease_png = "ui_fight#fight_txt_attackSpeedIncrease.png";
        ui_fight.fight_txt_attackSpeedReduce_png = "ui_fight#fight_txt_attackSpeedReduce.png";
        ui_fight.fight_txt_bloodDrinkingIncrease_png = "ui_fight#fight_txt_bloodDrinkingIncrease.png";
        ui_fight.fight_txt_crit_png = "ui_fight#fight_txt_crit.png";
        ui_fight.fight_txt_critDefenceIncrease_png = "ui_fight#fight_txt_critDefenceIncrease.png";
        ui_fight.fight_txt_critDefenceReduce_png = "ui_fight#fight_txt_critDefenceReduce.png";
        ui_fight.fight_txt_critIncrease_png = "ui_fight#fight_txt_critIncrease.png";
        ui_fight.fight_txt_critReduce_png = "ui_fight#fight_txt_critReduce.png";
        ui_fight.fight_txt_defenceOffsetIncrease_png = "ui_fight#fight_txt_defenceOffsetIncrease.png";
        ui_fight.fight_txt_dodge_png = "ui_fight#fight_txt_dodge.png";
        ui_fight.fight_txt_dodgeIncrease_png = "ui_fight#fight_txt_dodgeIncrease.png";
        ui_fight.fight_txt_dodgeReduce_png = "ui_fight#fight_txt_dodgeReduce.png";
        ui_fight.fight_txt_hitIncrease_png = "ui_fight#fight_txt_hitIncrease.png";
        ui_fight.fight_txt_hitReduce_png = "ui_fight#fight_txt_hitReduce.png";
        ui_fight.fight_txt_magicAttackIncrease_png = "ui_fight#fight_txt_magicAttackIncrease.png";
        ui_fight.fight_txt_magicAttackReduce_png = "ui_fight#fight_txt_magicAttackReduce.png";
        ui_fight.fight_txt_magicDefenceIncrease_png = "ui_fight#fight_txt_magicDefenceIncrease.png";
        ui_fight.fight_txt_magicDefenceReduce_png = "ui_fight#fight_txt_magicDefenceReduce.png";
        ui_fight.fight_txt_magicImmune_png = "ui_fight#fight_txt_magicImmune.png";
        ui_fight.fight_txt_movingSpeedIncrease_png = "ui_fight#fight_txt_movingSpeedIncrease.png";
        ui_fight.fight_txt_movingSpeedReduce_png = "ui_fight#fight_txt_movingSpeedReduce.png";
        ui_fight.fight_txt_physicalAttackIncrease_png = "ui_fight#fight_txt_physicalAttackIncrease.png";
        ui_fight.fight_txt_physicalAttackReduce_png = "ui_fight#fight_txt_physicalAttackReduce.png";
        ui_fight.fight_txt_physicalDefenceIncrease_png = "ui_fight#fight_txt_physicalDefenceIncrease.png";
        ui_fight.fight_txt_physicalDefenceReduce_png = "ui_fight#fight_txt_physicalDefenceReduce.png";
        ui_fight.fight_txt_physicalImmune_png = "ui_fight#fight_txt_physicalImmune.png";
        ui_fight.fight_txt_rebound_png = "ui_fight#fight_txt_rebound.png";
        ui_fight.fight_txt_skillsImmune_png = "ui_fight#fight_txt_skillsImmune.png";
        ui_fight.fill_hermeticengdown_png = "ui_fight#fill_hermeticengdown.png";
        ui_fight.fill_hermeticengdownfls_png = "ui_fight#fill_hermeticengdownfls.png";
        ui_fight.fill_hermeticenglight_png = "ui_fight#fill_hermeticenglight.png";
        ui_fight.fill_hermeticengup_png = "ui_fight#fill_hermeticengup.png";
        ui_fight.fill_hermeticengupfls_png = "ui_fight#fill_hermeticengupfls.png";
        ui_fight.freeze_png = "ui_fight#freeze.png";
        ui_fight.hermiCorrosion_png = "ui_fight#hermiCorrosion.png";
        ui_fight.hermiMagic_png = "ui_fight#hermiMagic.png";
        ui_fight.hermiPressure_png = "ui_fight#hermiPressure.png";
        ui_fight.hermiRoar_png = "ui_fight#hermiRoar.png";
        ui_fight.hermiViolent_png = "ui_fight#hermiViolent.png";
        ui_fight.ico_enegry_png = "ui_fight#ico_enegry.png";
        ui_fight.inr_hp_png = "ui_fight#inr_hp.png";
        ui_fight.inr_hp2_png = "ui_fight#inr_hp2.png";
        ui_fight.levelUP_png = "ui_fight#levelUP.png";
        ui_fight.lvlRect_png = "ui_fight#lvlRect.png";
        ui_fight.magicShieldCharm_png = "ui_fight#magicShieldCharm.png";
        ui_fight.normalAnger_png = "ui_fight#normalAnger.png";
        ui_fight.normalShieldCharm_png = "ui_fight#normalShieldCharm.png";
        ui_fight.ntc_replay_png = "ui_fight#ntc_replay.png";
        ui_fight.readytostart_png = "ui_fight#readytostart.png";
        ui_fight.ready_circle_png = "ui_fight#ready_circle.png";
        ui_fight.resultTitle_lose_png = "ui_fight#resultTitle_lose.png";
        ui_fight.resultTitle_win_png = "ui_fight#resultTitle_win.png";
        ui_fight.silence_png = "ui_fight#silence.png";
        ui_fight.star_png = "ui_fight#star.png";
        ui_fight.superAnger_png = "ui_fight#superAnger.png";
        ui_fight.title_pause_png = "ui_fight#title_pause.png";
        ui_fight.tnk_engnew_png = "ui_fight#tnk_engnew.png";
        ui_fight.tnk_hpnew_png = "ui_fight#tnk_hpnew.png";
        ui_fight.und_heronew_png = "ui_fight#und_heronew.png";
        ui_fight.waveunder_png = "ui_fight#waveunder.png";
        ui_fight.wrd_randomskill_png = "ui_fight#wrd_randomskill.png";
    })(ui_fight = res.ui_fight || (res.ui_fight = {}));
})(res || (res = {}));
var res;
(function (res) {
    var ui_film;
    (function (ui_film) {
        ui_film.randomgy_png = "ui_film#randomgy.png";
    })(ui_film = res.ui_film || (res.ui_film = {}));
})(res || (res = {}));
var res;
(function (res) {
    var ui_hermetic;
    (function (ui_hermetic) {
        ui_hermetic.blankpattern_png = "ui_hermetic#blankpattern.png";
        ui_hermetic.blk_hermeticinnew_png = "ui_hermetic#blk_hermeticinnew.png";
        ui_hermetic.blk_heroorweapon_png = "ui_hermetic#blk_heroorweapon.png";
        ui_hermetic.blk_skillbanknew_png = "ui_hermetic#blk_skillbanknew.png";
        ui_hermetic.btn_save_png = "ui_hermetic#btn_save.png";
        ui_hermetic.ntc_initiativenew_png = "ui_hermetic#ntc_initiativenew.png";
        ui_hermetic.ntc_ironedgenew_png = "ui_hermetic#ntc_ironedgenew.png";
        ui_hermetic.ntc_passivenew_png = "ui_hermetic#ntc_passivenew.png";
        ui_hermetic.titile_hermetic_png = "ui_hermetic#titile_hermetic.png";
        ui_hermetic.title_skillget_png = "ui_hermetic#title_skillget.png";
        ui_hermetic.title_skillupgrade_png = "ui_hermetic#title_skillupgrade.png";
    })(ui_hermetic = res.ui_hermetic || (res.ui_hermetic = {}));
})(res || (res = {}));
var res;
(function (res) {
    var ui_hero;
    (function (ui_hero) {
        ui_hero.A_png = "ui_hero#A.png";
        ui_hero.B_png = "ui_hero#B.png";
        ui_hero.bg_trainBtn_png = "ui_hero#bg_trainBtn.png";
        ui_hero.blk_normaleqp_focus_png = "ui_hero#blk_normaleqp_focus.png";
        ui_hero.blk_normaleqp_unfocus_png = "ui_hero#blk_normaleqp_unfocus.png";
        ui_hero.blk_weaponinfo_png = "ui_hero#blk_weaponinfo.png";
        ui_hero.btn_culture1_png = "ui_hero#btn_culture1.png";
        ui_hero.btn_culture2_png = "ui_hero#btn_culture2.png";
        ui_hero.btn_detail1_png = "ui_hero#btn_detail1.png";
        ui_hero.btn_detail2_png = "ui_hero#btn_detail2.png";
        ui_hero.btn_fullgrade_png = "ui_hero#btn_fullgrade.png";
        ui_hero.btn_onestrengthen_png = "ui_hero#btn_onestrengthen.png";
        ui_hero.btn_strengthen_png = "ui_hero#btn_strengthen.png";
        ui_hero.btn_train_png = "ui_hero#btn_train.png";
        ui_hero.btn_trainUp_png = "ui_hero#btn_trainUp.png";
        ui_hero.btn_upgrade_png = "ui_hero#btn_upgrade.png";
        ui_hero.btn_upSkill1_png = "ui_hero#btn_upSkill1.png";
        ui_hero.btn_upSkill2_png = "ui_hero#btn_upSkill2.png";
        ui_hero.C_png = "ui_hero#C.png";
        ui_hero.cov_washingbar_png = "ui_hero#cov_washingbar.png";
        ui_hero.D_png = "ui_hero#D.png";
        ui_hero.line1_png = "ui_hero#line1.png";
        ui_hero.midline_png = "ui_hero#midline.png";
        ui_hero.mixSkillItemBg_png = "ui_hero#mixSkillItemBg.png";
        ui_hero.S_png = "ui_hero#S.png";
        ui_hero.skillItemBg_png = "ui_hero#skillItemBg.png";
        ui_hero.wrd_level_png = "ui_hero#wrd_level.png";
        ui_hero.wrd_upgrade_png = "ui_hero#wrd_upgrade.png";
        ui_hero.btn_upLvl_png = "ui_hero2#btn_upLvl.png";
        ui_hero.fazhen_png = "ui_hero2#fazhen.png";
        ui_hero.ico_crown_png = "ui_hero2#ico_crown.png";
        ui_hero.job_1_png = "ui_hero2#job_1.png";
        ui_hero.job_2_png = "ui_hero2#job_2.png";
        ui_hero.job_3_png = "ui_hero2#job_3.png";
        ui_hero.job_4_png = "ui_hero2#job_4.png";
        ui_hero.quality_bg_png = "ui_hero2#quality_bg.png";
        ui_hero.quality_title_png = "ui_hero2#quality_title.png";
    })(ui_hero = res.ui_hero || (res.ui_hero = {}));
})(res || (res = {}));
var res;
(function (res) {
    var ui_home;
    (function (ui_home) {
        ui_home.btn_signout_png = "ui_home#btn_signout.png";
        ui_home.critx10_png = "ui_home#critx10.png";
        ui_home.critx2_png = "ui_home#critx2.png";
        ui_home.critx3_png = "ui_home#critx3.png";
        ui_home.critx5_png = "ui_home#critx5.png";
        ui_home.dice_png = "ui_home#dice.png";
        ui_home.home_chat_scrollbar_png = "ui_home#home_chat_scrollbar.png";
        ui_home.home_chat_scroll_bg_png = "ui_home#home_chat_scroll_bg.png";
        ui_home.home_chat_send_png = "ui_home#home_chat_send.png";
        ui_home.home_modifyHead_png = "ui_home#home_modifyHead.png";
        ui_home.home_name_bg_png = "ui_home#home_name_bg.png";
        ui_home.home_option_png = "ui_home#home_option.png";
        ui_home.home_sound_off_png = "ui_home#home_sound_off.png";
        ui_home.home_sound_on_png = "ui_home#home_sound_on.png";
        ui_home.home_ui_cornor_bg_png = "ui_home#home_ui_cornor_bg.png";
        ui_home.home_ui_cornor_bl_png = "ui_home#home_ui_cornor_bl.png";
        ui_home.home_ui_cornor_head2_png = "ui_home#home_ui_cornor_head2.png";
        ui_home.home_ui_icon_bg_png = "ui_home#home_ui_icon_bg.png";
        ui_home.home_vip_icon_png = "ui_home#home_vip_icon.png";
        ui_home.icon_7up_png = "ui_home#icon_7up.png";
        ui_home.icon_bag_png = "ui_home#icon_bag.png";
        ui_home.icon_charge_png = "ui_home#icon_charge.png";
        ui_home.icon_daily_png = "ui_home#icon_daily.png";
        ui_home.icon_feedback_png = "ui_home#icon_feedback.png";
        ui_home.icon_firstcoin_png = "ui_home#icon_firstcoin.png";
        ui_home.icon_getmemoney_png = "ui_home#icon_getmemoney.png";
        ui_home.icon_greatdaily_png = "ui_home#icon_greatdaily.png";
        ui_home.icon_hermetic_png = "ui_home#icon_hermetic.png";
        ui_home.icon_hero_png = "ui_home#icon_hero.png";
        ui_home.icon_mail_png = "ui_home#icon_mail.png";
        ui_home.icon_mixture_png = "ui_home#icon_mixture.png";
        ui_home.icon_rank_png = "ui_home#icon_rank.png";
        ui_home.icon_sign_png = "ui_home#icon_sign.png";
        ui_home.icon_signin_png = "ui_home#icon_signin.png";
        ui_home.icon_task_png = "ui_home#icon_task.png";
        ui_home.ico_alchemy_png = "ui_home#ico_alchemy.png";
        ui_home.ntc_hmt_png = "ui_home#ntc_hmt.png";
        ui_home.pat_modifyHead_png = "ui_home#pat_modifyHead.png";
        ui_home.vip_0_png = "ui_home#vip_0.png";
        ui_home.vip_1_png = "ui_home#vip_1.png";
        ui_home.vip_2_png = "ui_home#vip_2.png";
        ui_home.vip_3_png = "ui_home#vip_3.png";
        ui_home.vip_4_png = "ui_home#vip_4.png";
        ui_home.vip_5_png = "ui_home#vip_5.png";
        ui_home.vip_6_png = "ui_home#vip_6.png";
        ui_home.vip_7_png = "ui_home#vip_7.png";
        ui_home.vip_8_png = "ui_home#vip_8.png";
        ui_home.vip_9_png = "ui_home#vip_9.png";
        ui_home.wrd_moneycirtical_png = "ui_home#wrd_moneycirtical.png";
    })(ui_home = res.ui_home || (res.ui_home = {}));
})(res || (res = {}));
var res;
(function (res) {
    var ui_homebg;
    (function (ui_homebg) {
        ui_homebg.blk9_shadow_png = "ui_homebg#blk9_shadow.png";
        ui_homebg.blk_name_png = "ui_homebg#blk_name.png";
        ui_homebg.blk_name_locked_png = "ui_homebg#blk_name_locked.png";
        ui_homebg.btn_blacksmith_png = "ui_homebg#btn_blacksmith.png";
        ui_homebg.btn_blacksmith_locked_png = "ui_homebg#btn_blacksmith_locked.png";
        ui_homebg.btn_duplicate_png = "ui_homebg#btn_duplicate.png";
        ui_homebg.btn_duplicate_locked_png = "ui_homebg#btn_duplicate_locked.png";
        ui_homebg.btn_fightinghouse_png = "ui_homebg#btn_fightinghouse.png";
        ui_homebg.btn_fightinghouse_locked_png = "ui_homebg#btn_fightinghouse_locked.png";
        ui_homebg.btn_guardtower_png = "ui_homebg#btn_guardtower.png";
        ui_homebg.btn_guardtower_locked_png = "ui_homebg#btn_guardtower_locked.png";
        ui_homebg.btn_guild_png = "ui_homebg#btn_guild.png";
        ui_homebg.btn_mirrorwrd_png = "ui_homebg#btn_mirrorwrd.png";
        ui_homebg.btn_mirrorwrd_locked_png = "ui_homebg#btn_mirrorwrd_locked.png";
        ui_homebg.btn_roaric_png = "ui_homebg#btn_roaric.png";
        ui_homebg.btn_roaric_locked_png = "ui_homebg#btn_roaric_locked.png";
        ui_homebg.btn_seceratshop_png = "ui_homebg#btn_seceratshop.png";
        ui_homebg.btn_shop_png = "ui_homebg#btn_shop.png";
        ui_homebg.btn_shop_locked_png = "ui_homebg#btn_shop_locked.png";
        ui_homebg.btn_wishpool_png = "ui_homebg#btn_wishpool.png";
        ui_homebg.btn_wishpool_locked_png = "ui_homebg#btn_wishpool_locked.png";
        ui_homebg.cloud1_png = "ui_homebg#cloud1.png";
        ui_homebg.cloud2_png = "ui_homebg#cloud2.png";
        ui_homebg.floor1_png = "ui_homebg#floor1.png";
        ui_homebg.floor2_png = "ui_homebg#floor2.png";
        ui_homebg.floor3_png = "ui_homebg#floor3.png";
        ui_homebg.floor4_png = "ui_homebg#floor4.png";
        ui_homebg.floor5_png = "ui_homebg#floor5.png";
        ui_homebg.floor6_png = "ui_homebg#floor6.png";
        ui_homebg.floor7_png = "ui_homebg#floor7.png";
        ui_homebg.floor8_png = "ui_homebg#floor8.png";
        ui_homebg.ntc_selectbud_png = "ui_homebg#ntc_selectbud.png";
    })(ui_homebg = res.ui_homebg || (res.ui_homebg = {}));
})(res || (res = {}));
var res;
(function (res) {
    var ui_login;
    (function (ui_login) {
        ui_login.blk9_user_png = "ui_login#blk9_user.png";
        ui_login.blk_area_png = "ui_login#blk_area.png";
        ui_login.btn_changearea_png = "ui_login#btn_changearea.png";
        ui_login.btn_close_png = "ui_login#btn_close.png";
        ui_login.btn_fastenter_png = "ui_login#btn_fastenter.png";
        ui_login.btn_login_png = "ui_login#btn_login.png";
        ui_login.btn_logout_png = "ui_login#btn_logout.png";
        ui_login.btn_notice_png = "ui_login#btn_notice.png";
        ui_login.btn_passworldfinding_png = "ui_login#btn_passworldfinding.png";
        ui_login.btn_select_png = "ui_login#btn_select.png";
        ui_login.btn_signin_png = "ui_login#btn_signin.png";
        ui_login.btn_start_png = "ui_login#btn_start.png";
        ui_login.btn_unselect_png = "ui_login#btn_unselect.png";
        ui_login.tag_grn_png = "ui_login#tag_grn.png";
        ui_login.tag_new_png = "ui_login#tag_new.png";
        ui_login.tag_purple_png = "ui_login#tag_purple.png";
        ui_login.tag_red_png = "ui_login#tag_red.png";
        ui_login.tag_yellow_png = "ui_login#tag_yellow.png";
        ui_login.title_allserver_png = "ui_login#title_allserver.png";
        ui_login.title_login_png = "ui_login#title_login.png";
        ui_login.title_nl_png = "ui_login#title_nl.png";
        ui_login.title_password_png = "ui_login#title_password.png";
        ui_login.title_signin_png = "ui_login#title_signin.png";
        ui_login.wrd_png = "ui_login#wrd.png";
        ui_login.wrd_email_png = "ui_login#wrd_email.png";
        ui_login.wrd_passwordcomfirm_png = "ui_login#wrd_passwordcomfirm.png";
        ui_login.wrd_passworld_png = "ui_login#wrd_passworld.png";
        ui_login.wrd_username_png = "ui_login#wrd_username.png";
    })(ui_login = res.ui_login || (res.ui_login = {}));
})(res || (res = {}));
var res;
(function (res) {
    var ui_lottery;
    (function (ui_lottery) {
        ui_lottery.blk_result_png = "ui_lottery#blk_result.png";
        ui_lottery.lightnormalbox_png = "ui_lottery#lightnormalbox.png";
        ui_lottery.lightsuperbox_png = "ui_lottery#lightsuperbox.png";
        ui_lottery.normalbox_png = "ui_lottery#normalbox.png";
        ui_lottery.ntc_10blueitem_png = "ui_lottery#ntc_10blueitem.png";
        ui_lottery.ntc_10hero_png = "ui_lottery#ntc_10hero.png";
        ui_lottery.superbox_png = "ui_lottery#superbox.png";
    })(ui_lottery = res.ui_lottery || (res.ui_lottery = {}));
})(res || (res = {}));
var res;
(function (res) {
    var ui_mail;
    (function (ui_mail) {
        ui_mail.annex_png = "ui_mail#annex.png";
        ui_mail.from_png = "ui_mail#from.png";
        ui_mail.ntc_noitem_png = "ui_mail#ntc_noitem.png";
    })(ui_mail = res.ui_mail || (res.ui_mail = {}));
})(res || (res = {}));
var res;
(function (res) {
    var ui_mirrorworld;
    (function (ui_mirrorworld) {
        ui_mirrorworld.bg_elfblue_png = "ui_mirrorworld#bg_elfblue.png";
        ui_mirrorworld.bg_elfred_png = "ui_mirrorworld#bg_elfred.png";
        ui_mirrorworld.bg_glassblue_png = "ui_mirrorworld#bg_glassblue.png";
        ui_mirrorworld.bg_glassred_png = "ui_mirrorworld#bg_glassred.png";
        ui_mirrorworld.btn_level_png = "ui_mirrorworld#btn_level.png";
        ui_mirrorworld.btn_viewMe_png = "ui_mirrorworld#btn_viewMe.png";
        ui_mirrorworld.ntc_challengable_png = "ui_mirrorworld#ntc_challengable.png";
        ui_mirrorworld.ntc_inabattle_png = "ui_mirrorworld#ntc_inabattle.png";
    })(ui_mirrorworld = res.ui_mirrorworld || (res.ui_mirrorworld = {}));
})(res || (res = {}));
var res;
(function (res) {
    var ui_mt;
    (function (ui_mt) {
        ui_mt.blk_level_open_png = "ui_mt#blk_level_open.png";
        ui_mt.ico_lvl_0_png = "ui_mt#ico_lvl_0.png";
        ui_mt.ico_lvl_1_png = "ui_mt#ico_lvl_1.png";
        ui_mt.ico_lvl_2_png = "ui_mt#ico_lvl_2.png";
        ui_mt.ico_lvl_3_png = "ui_mt#ico_lvl_3.png";
        ui_mt.ico_lvl_4_png = "ui_mt#ico_lvl_4.png";
        ui_mt.ico_lvl_5_png = "ui_mt#ico_lvl_5.png";
    })(ui_mt = res.ui_mt || (res.ui_mt = {}));
})(res || (res = {}));
var res;
(function (res) {
    var ui_num;
    (function (ui_num) {
        ui_num.sty_gold_png = "ui/ui_num/sty_gold.png";
        ui_num.sty_herolevel_png = "ui/ui_num/sty_herolevel.png";
        ui_num.sty_vip_png = "ui/ui_num/sty_vip.png";
    })(ui_num = res.ui_num || (res.ui_num = {}));
})(res || (res = {}));
var res;
(function (res) {
    var ui_panel;
    (function (ui_panel) {
        ui_panel.bar_loading_png = "ui_panel#bar_loading.png";
        ui_panel.blk9_babble3_png = "ui_panel#blk9_babble3.png";
        ui_panel.blk9_babble4_png = "ui_panel#blk9_babble4.png";
        ui_panel.blk9_bag_png = "ui_panel#blk9_bag.png";
        ui_panel.blk9_barbg_png = "ui_panel#blk9_barbg.png";
        ui_panel.blk9_challenger_png = "ui_panel#blk9_challenger.png";
        ui_panel.blk9_challengerinfo_png = "ui_panel#blk9_challengerinfo.png";
        ui_panel.blk9_diamond_png = "ui_panel#blk9_diamond.png";
        ui_panel.blk9_gold_png = "ui_panel#blk9_gold.png";
        ui_panel.blk9_gold1_png = "ui_panel#blk9_gold1.png";
        ui_panel.blk9_gold2_png = "ui_panel#blk9_gold2.png";
        ui_panel.blk9_heroblankl_png = "ui_panel#blk9_heroblankl.png";
        ui_panel.blk9_heroform_png = "ui_panel#blk9_heroform.png";
        ui_panel.blk9_heronameblank_png = "ui_panel#blk9_heronameblank.png";
        ui_panel.blk9_info_png = "ui_panel#blk9_info.png";
        ui_panel.blk9_ininfo_png = "ui_panel#blk9_ininfo.png";
        ui_panel.blk9_innerforredblank_png = "ui_panel#blk9_innerforredblank.png";
        ui_panel.blk9_inputline_png = "ui_panel#blk9_inputline.png";
        ui_panel.blk9_item_png = "ui_panel#blk9_item.png";
        ui_panel.blk9_item1_png = "ui_panel#blk9_item1.png";
        ui_panel.blk9_itembox_png = "ui_panel#blk9_itembox.png";
        ui_panel.blk9_ltabbg_png = "ui_panel#blk9_ltabbg.png";
        ui_panel.blk9_m_png = "ui_panel#blk9_m.png";
        ui_panel.blk9_money_png = "ui_panel#blk9_money.png";
        ui_panel.blk9_rankstrip_png = "ui_panel#blk9_rankstrip.png";
        ui_panel.blk9_rtabbg_png = "ui_panel#blk9_rtabbg.png";
        ui_panel.blk9_shopitem_png = "ui_panel#blk9_shopitem.png";
        ui_panel.blk9_skill_png = "ui_panel#blk9_skill.png";
        ui_panel.blk9_skill2_png = "ui_panel#blk9_skill2.png";
        ui_panel.blk9_skilltitlebg_png = "ui_panel#blk9_skilltitlebg.png";
        ui_panel.blk9_stepone_png = "ui_panel#blk9_stepone.png";
        ui_panel.blk9_steptwo_png = "ui_panel#blk9_steptwo.png";
        ui_panel.blk9_talent_png = "ui_panel#blk9_talent.png";
        ui_panel.blk9_talentg_png = "ui_panel#blk9_talentg.png";
        ui_panel.blk9_transparent_png = "ui_panel#blk9_transparent.png";
        ui_panel.blk9_transparentred_png = "ui_panel#blk9_transparentred.png";
        ui_panel.blk9_trialcard_png = "ui_panel#blk9_trialcard.png";
        ui_panel.blk9_vipblk2_png = "ui_panel#blk9_vipblk2.png";
        ui_panel.blk_headcooper_png = "ui_panel#blk_headcooper.png";
        ui_panel.blk_headgold_png = "ui_panel#blk_headgold.png";
        ui_panel.blk_headnormal_png = "ui_panel#blk_headnormal.png";
        ui_panel.blk_headsilver_png = "ui_panel#blk_headsilver.png";
        ui_panel.blk_hero_png = "ui_panel#blk_hero.png";
        ui_panel.blk_nums_png = "ui_panel#blk_nums.png";
        ui_panel.blk_rankandfunction_png = "ui_panel#blk_rankandfunction.png";
        ui_panel.btn_back1_png = "ui_panel#btn_back1.png";
        ui_panel.btn_back2_png = "ui_panel#btn_back2.png";
        ui_panel.btn_close_png = "ui_panel#btn_close.png";
        ui_panel.btn_contractcomfirm_focus_png = "ui_panel#btn_contractcomfirm_focus.png";
        ui_panel.btn_contractcomfirm_unfocus_png = "ui_panel#btn_contractcomfirm_unfocus.png";
        ui_panel.btn_info_focus_png = "ui_panel#btn_info_focus.png";
        ui_panel.btn_info_unfocus_png = "ui_panel#btn_info_unfocus.png";
        ui_panel.combatEff_png = "ui_panel#combatEff.png";
        ui_panel.common_infoTitle_png = "ui_panel#common_infoTitle.png";
        ui_panel.copy_level_blanket_png = "ui_panel#copy_level_blanket.png";
        ui_panel.cornerBL_png = "ui_panel#cornerBL.png";
        ui_panel.cornerTL_png = "ui_panel#cornerTL.png";
        ui_panel.cov_scrap_png = "ui_panel#cov_scrap.png";
        ui_panel.cov_task_png = "ui_panel#cov_task.png";
        ui_panel.eqp_1_png = "ui_panel#eqp_1.png";
        ui_panel.eqp_2_png = "ui_panel#eqp_2.png";
        ui_panel.eqp_3_png = "ui_panel#eqp_3.png";
        ui_panel.eqp_4_png = "ui_panel#eqp_4.png";
        ui_panel.eqp_5_png = "ui_panel#eqp_5.png";
        ui_panel.eqp_6_png = "ui_panel#eqp_6.png";
        ui_panel.eqp_7_png = "ui_panel#eqp_7.png";
        ui_panel.heroIcon_jpg = "ui_panel#heroIcon.jpg";
        ui_panel.heroIconMask_png = "ui_panel#heroIconMask.png";
        ui_panel.icon_item_default_png = "ui_panel#icon_item_default.png";
        ui_panel.icon_lose_png = "ui_panel#icon_lose.png";
        ui_panel.icon_win_png = "ui_panel#icon_win.png";
        ui_panel.leaderExp_png = "ui_panel#leaderExp.png";
        ui_panel.levelUP_png = "ui_panel#levelUP.png";
        ui_panel.ntc_boss_png = "ui_panel#ntc_boss.png";
        ui_panel.ntc_soldout_png = "ui_panel#ntc_soldout.png";
        ui_panel.point_png = "ui_panel#point.png";
        ui_panel.skillIcon_png = "ui_panel#skillIcon.png";
        ui_panel.under_package_png = "ui_panel#under_package.png";
        ui_panel.und_info_png = "ui_panel#und_info.png";
        ui_panel.und_myrank_png = "ui_panel#und_myrank.png";
        ui_panel.wrd_yougotahero_png = "ui_panel#wrd_yougotahero.png";
    })(ui_panel = res.ui_panel || (res.ui_panel = {}));
})(res || (res = {}));
var res;
(function (res) {
    var ui_quest;
    (function (ui_quest) {
        ui_quest.btn_receive_png = "ui_quest#btn_receive.png";
        ui_quest.ntc_questicon_png = "ui_quest#ntc_questicon.png";
        ui_quest.ntc_reward_png = "ui_quest#ntc_reward.png";
    })(ui_quest = res.ui_quest || (res.ui_quest = {}));
})(res || (res = {}));
var res;
(function (res) {
    var ui_rank;
    (function (ui_rank) {
        ui_rank.blk_tagfocus_png = "ui_rank#blk_tagfocus.png";
        ui_rank.blk_tagunfocus_png = "ui_rank#blk_tagunfocus.png";
        ui_rank.blk_title_png = "ui_rank#blk_title.png";
        ui_rank.btn_myrank_png = "ui_rank#btn_myrank.png";
        ui_rank.ntc_cut_png = "ui_rank#ntc_cut.png";
        ui_rank.ntc_towerfloor_png = "ui_rank#ntc_towerfloor.png";
        ui_rank.title_rank_png = "ui_rank#title_rank.png";
        ui_rank.wrd_herofocus_png = "ui_rank#wrd_herofocus.png";
        ui_rank.wrd_herounfocus_png = "ui_rank#wrd_herounfocus.png";
        ui_rank.wrd_towerfocus_png = "ui_rank#wrd_towerfocus.png";
        ui_rank.wrd_towerunfocus_png = "ui_rank#wrd_towerunfocus.png";
        ui_rank.wrd_unionfocus_png = "ui_rank#wrd_unionfocus.png";
        ui_rank.wrd_unionunfocus_png = "ui_rank#wrd_unionunfocus.png";
    })(ui_rank = res.ui_rank || (res.ui_rank = {}));
})(res || (res = {}));
var res;
(function (res) {
    var ui_secratshop;
    (function (ui_secratshop) {
        ui_secratshop.blk_secratshope_png = "ui_secratshop#blk_secratshope.png";
        ui_secratshop.blk_title_png = "ui_secratshop#blk_title.png";
        ui_secratshop.wrd_title_png = "ui_secratshop#wrd_title.png";
        ui_secratshop.wrd_title2_png = "ui_secratshop#wrd_title2.png";
    })(ui_secratshop = res.ui_secratshop || (res.ui_secratshop = {}));
})(res || (res = {}));
var res;
(function (res) {
    var ui_tower;
    (function (ui_tower) {
        ui_tower.bg_ball_png = "ui_tower#bg_ball.png";
        ui_tower.bg_platform_png = "ui_tower#bg_platform.png";
        ui_tower.blk_challenge_png = "ui_tower#blk_challenge.png";
        ui_tower.btn_autochallenge_png = "ui_tower#btn_autochallenge.png";
        ui_tower.btn_challenge_png = "ui_tower#btn_challenge.png";
        ui_tower.btn_gift2_png = "ui_tower#btn_gift2.png";
        ui_tower.btn_scoreshop_png = "ui_tower#btn_scoreshop.png";
        ui_tower.ntc_receivable_png = "ui_tower#ntc_receivable.png";
        ui_tower.ntc_unreceivable_png = "ui_tower#ntc_unreceivable.png";
        ui_tower.title_blow_png = "ui_tower#title_blow.png";
        ui_tower.wrd_level_png = "ui_tower#wrd_level.png";
    })(ui_tower = res.ui_tower || (res.ui_tower = {}));
})(res || (res = {}));
var res;
(function (res) {
    var ui_trial;
    (function (ui_trial) {
        ui_trial.bg_pCopy_0_0_png = "ui_trial#bg_pCopy_0_0.png";
        ui_trial.bg_pCopy_0_1_png = "ui_trial#bg_pCopy_0_1.png";
        ui_trial.bg_pCopy_0_2_png = "ui_trial#bg_pCopy_0_2.png";
        ui_trial.bg_pCopy_1_0_png = "ui_trial#bg_pCopy_1_0.png";
        ui_trial.bg_pCopy_1_1_png = "ui_trial#bg_pCopy_1_1.png";
        ui_trial.bg_pCopy_1_2_png = "ui_trial#bg_pCopy_1_2.png";
        ui_trial.bg_pCopy_2_0_png = "ui_trial#bg_pCopy_2_0.png";
        ui_trial.bg_pCopy_2_1_png = "ui_trial#bg_pCopy_2_1.png";
        ui_trial.bg_pCopy_2_2_png = "ui_trial#bg_pCopy_2_2.png";
        ui_trial.totum_1_png = "ui_trial#totum_1.png";
        ui_trial.totum_2_png = "ui_trial#totum_2.png";
        ui_trial.totum_3_png = "ui_trial#totum_3.png";
    })(ui_trial = res.ui_trial || (res.ui_trial = {}));
})(res || (res = {}));
var res;
(function (res) {
    var ui_vip;
    (function (ui_vip) {
        ui_vip.blk_title_png = "ui_vip#blk_title.png";
        ui_vip.btn_money_png = "ui_vip#btn_money.png";
        ui_vip.btn_vipinfo_png = "ui_vip#btn_vipinfo.png";
        ui_vip.title_png = "ui_vip#title.png";
        ui_vip.titlef_png = "ui_vip#titlef.png";
        ui_vip.vip_png = "ui_vip#vip.png";
    })(ui_vip = res.ui_vip || (res.ui_vip = {}));
})(res || (res = {}));
